login:
    path: /auth/login
    methods: GET
    # controller: app\Controller\AuthController::loginPage
    controller: app\Controller\SecurityController::login


registry:
    path: /auth/registry
    methods: GET
    #controller: app\Controller\AuthController::registryPage
    controller: app\Controller\SecurityController::registry

login_Proc:
    path: /auth/login
    methods: POST
    #controller: app\Controller\AuthController::login
    controller: app\Controller\SecurityController::loginProc


registry_Proc:
    path: /auth/registry
    methods: POST
    #controller: app\Controller\AuthController::registry
    controller: app\Controller\SecurityController::registryProc

logout:
    path: /auth/logout
    methods: GET
    #controller: app\Controller\AuthController::logout
    controller: app\Controller\SecurityController::logout
