room_create_page:
    path: /room/create
    methods: GET
    controller: app\Controller\RoomController::createPage

room_create:
    path: /room/create
    methods: POST
    controller: app\Controller\RoomController::create

room_join:
    path: /room/join/{id}
    methods: POST
    controller: app\Controller\RoomController::join
